name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: './backend/package.json'
        
    - name: Install dependencies
      run: |
        cd backend
        npm install
        
    - name: Build frontend (if needed)
      run: |
        echo "Frontend is static HTML, no build needed"
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: './frontend'
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v2
